# Generated by Django 5.1.5 on 2025-01-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='font_size',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], default='Daily', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Light', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
