# Generated by Django 5.1.5 on 2025-01-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_customuser_data_sharing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='data_sharing',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_visibility',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='theme',
        ),
        migrations.AddField(
            model_name='customuser',
            name='font_style',
            field=models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif'), ('monospace', 'Monospace')], default='sans-serif', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='layout_style',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_color',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
    ]
