# Generated by Django 5.1.5 on 2025-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_remove_customuser_data_sharing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
