# Generated by Django 5.1.5 on 2025-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_customuser_data_sharing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='layout_style',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='list', max_length=10),
        ),
    ]
